# environment_py2.yml
# Configuration file for creating a Conda Environment with dependencies needed for Tethys Platform.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment_py2.yml

name: tethys

channels:
- tethysplatform
- conda-forge
- defaults

dependencies:
- python=2.7*
- django=1.11.*
- django-filter=1.0*
- djangorestframework=3.6*
- bokeh=0.12*
- future=0.16*
- hs_restclient
- paste=2.0*
- psycopg2=2.7*
- sqlalchemy=1.1*
- requests=2.18*
- selenium=3.4*
- coverage=4*
- docker-py<1.10
- geoalchemy2=0.4*
- owslib=0.14*
- pip=9.0*
- pillow
- plotly
- postgresql
- postgis
- pycrypto=2.6*
- pyopenssl=16.2*
- mock
- factory_boy
- tethys_dataset_services>=1.7.0
- pip:
    - django-gravatar2>=1.4.0,<1.5.0
    - django-bootstrap3>=8.2.0,<8.3.0
    - django-model-utils>=3.0.0,<3.1.0
    - django-guardian>=1.4.0,<1.5.0
    - django-simple-captcha>=0.5.0,<0.6.0
    - django-termsandconditions>=1.1.0,<1.2.0
    - django-session-security>=2.5.0,<2.6.0
    - condorpy>=0.3.0,<0.4.0
    - social-auth-app-django>=1.2.0,<1.3.0
    - python_social_auth
    - requests-mock
